### ISSUE TITLE
After 1.5.2 the 'auto_create_group' parameter seems to be ignored.

### ISSUE THREAD

**Issue by jonathanjuursema** [aws/amazon-cloudwatch-logs-for-fluent-bit#96] opened 2020-09-18 08:57 UTC
_Cross posting this here from [this](https://github.com/aws/aws-for-fluent-bit/issues/74) issue in the `aws-for-fluent-bit` repo. Based on the discussion there this seems to be a regression._

It looks like fluentbit 1.5.6 ignores the `auto_create_group` parameter for the AWS Cloudwatch output plugin. For comparison, here's a sample logging of aws-for-fluent-bit 2.6.1:
```
AWS for Fluent Bit Container Image Version 2.6.1
Fluent Bit v1.5.2
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/09/18 08:13:03] [ info] [engine] started (pid=1)
[2020/09/18 08:13:03] [ info] [storage] version=1.0.4, initializing...
[2020/09/18 08:13:03] [ info] [storage] in-memory
[2020/09/18 08:13:03] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/09/18 08:13:03] [ info] [filter:kubernetes:kubernetes.0] https=1 host=xxx.gr7.eu-west-1.eks.amazonaws.com port=443
[2020/09/18 08:13:03] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2020/09/18 08:13:03] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2020/09/18 08:13:03] [ info] [filter:kubernetes:kubernetes.0] API server connectivity OK
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter log_group = '/applications/eks-fluentbit/sandbox-cluster'"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_prefix = 'fluentbit-'"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter log_stream = ''"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter region = 'eu-west-1'"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter log_key = ''"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter role_arn = ''"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter auto_create_group = 'false'"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter endpoint = ''"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter sts_endpoint = ''"
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter credentials_endpoint = "
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter log_format = ''"
[2020/09/18 08:13:03] [ info] [sp] stream processor started
[2020/09/18 08:13:04] [ info] inotify_fs_add(): inode=81808779 watch_fd=1 name=/var/log/containers/app-2048-744b65db67-7vp92_default_app-2048-395f15844e966d1df1d574b7684136c8a155b32da5f07d18cc549c19e5874c2f.log
[2020/09/18 08:13:04] [ info] inotify_fs_add(): inode=95421297 watch_fd=2 name=/var/log/containers/alb-ingress-controller-66dfcf4c7b-wk4bx_kube-system_alb-ingress-controller-67c96153d9a7d84e82c5fbaaec336658d29d31791ecc19a217ad70c2e683999a.log
[2020/09/18 08:13:04] [ info] inotify_fs_add(): inode=38798863 watch_fd=3 name=/var/log/containers/aws-node-7vt9x_kube-system_aws-node-14b94d55972a532cb6962c1d3500afce936fa7bf78cac1b05ca56b78a6f9ece1.log
[2020/09/18 08:13:04] [ info] inotify_fs_add(): inode=38799693 watch_fd=4 name=/var/log/containers/coredns-6658f9f447-jftdc_kube-system_coredns-4b27f73b9ba0dae778c3eba0e899c6753bf817cd11b0b98c2fedaa7c1eda43c2.log
[2020/09/18 08:13:04] [ info] inotify_fs_add(): inode=8465476 watch_fd=5 name=/var/log/containers/metrics-server-6bdf64df8c-9qbmq_kube-system_metrics-server-694a23ea90fde6c4f2dfd5eebf1b91beb8aa58340a1f2ca68787345d53bd196b.log
... happy times ...
```

An here's one for 2.7.0 in our environment:
```
AWS for Fluent Bit Container Image Version 2.7.0
Fluent Bit v1.5.6
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/09/18 08:19:11] [ info] [engine] started (pid=1)
[2020/09/18 08:19:11] [ info] [storage] version=1.0.5, initializing...
[2020/09/18 08:19:11] [ info] [storage] in-memory
[2020/09/18 08:19:11] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/09/18 08:19:11] [ info] [filter:kubernetes:kubernetes.0] https=1 host=xxx.gr7.eu-west-1.eks.amazonaws.com port=443
[2020/09/18 08:19:11] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2020/09/18 08:19:11] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2020/09/18 08:19:11] [ info] [filter:kubernetes:kubernetes.0] API server connectivity OK
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter log_group = '/applications/eks-fluentbit/sandbox-cluster'"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_prefix = 'fluentbit-'"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter log_stream_name = ''"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter region = 'eu-west-1'"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter log_key = ''"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter role_arn = ''"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter new_log_group_tags = ''"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter log_retention_days = '0'"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter endpoint = ''"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter sts_endpoint = ''"
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter credentials_endpoint = "
time="2020-09-18T08:19:11Z" level=info msg="[cloudwatch 0] plugin parameter log_format = ''"
[2020/09/18 08:19:11] [ info] [sp] stream processor started
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=24126733 watch_fd=1 name=/var/log/containers/app-2048-744b65db67-p9gqg_default_app-2048-c1a892b15f1eec7813e08bb52561895073c6b0706d73f0d5dc6592bdbcbb11f0.log
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=28402853 watch_fd=2 name=/var/log/containers/ubuntu-toolbox-79bfd58fb8-pwmjs_default_ubuntu-toolbox-940c495f99d2b36b4773dffe912679acb67abc3ee684be6c62ba168e7d8e101e.log
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=38798125 watch_fd=3 name=/var/log/containers/aws-node-qcq2v_kube-system_aws-node-5e9d32e8025abd0ee567e3cc0259fedbe24eeab16676718d53e71002983ab101.log
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=14686721 watch_fd=4 name=/var/log/containers/coredns-6658f9f447-wtfcj_kube-system_coredns-384a068a4e42b18a3b8739055507cd4526fe7d69f86b3c1c20a61a5030f633dd.log
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=263537 watch_fd=5 name=/var/log/containers/vpc-admission-webhook-67646bbf89-xg94g_kube-system_vpc-admission-webhook-a03047e4ff26a078391f4bb3fc76529dd3bcd71341d95c19b3a216a543872f0d.log
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=68163896 watch_fd=6 name=/var/log/containers/vpc-admission-webhook-deployment-6c4d68f76c-r9x49_kube-system_vpc-admission-webhook-aa186f5137b9b7d6d295710b2e30e29cc2200aeb06b4d1c838c5f883e01e6fa5.log
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=69262005 watch_fd=7 name=/var/log/containers/vpc-resource-controller-5b5bc46646-vxh4h_kube-system_vpc-resource-controller-b0a9fd2ec356f91674156e1745d681c111fb8bbdf6c1b8a6acbbfb5349680593.log
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=5255668 watch_fd=8 name=/var/log/containers/kube-proxy-nqc6g_kube-system_kube-proxy-0fbf8e1040048ea863d59cb7b9f74a260d2d36d03b8f6764993b0543c38ec2b8.log
[2020/09/18 08:19:11] [ info] inotify_fs_add(): inode=97625584 watch_fd=9 name=/var/log/containers/fluentbit-f4wls_kube-system_aws-for-fluent-bit-92814b8b79b757088aab1de7842e2e4a82b4a6fea800a06ffb9ff8e68705fab2.log
time="2020-09-18T08:19:17Z" level=error msg="AccessDeniedException: User: arn:aws:iam::xxx:user/fluentbit-sandbox-clus-eu-west-1 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-west-1:xxx:log-group:/applications/eks-fluentbit/sandbox-cluster:log-stream:\n\tstatus code: 400, request id: 069f9041-cae2-4d20-8e33-4e5706cfe914"
time="2020-09-18T08:19:17Z" level=error msg="AccessDeniedException: User: arn:aws:iam::xxx:user/fluentbit-sandbox-clus-eu-west-1 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-west-1:xxx:log-group:/applications/eks-fluentbit/sandbox-cluster:log-stream:\n\tstatus code: 400, request id: 1103959f-e52e-488f-b547-28a85cd591db"
time="2020-09-18T08:19:17Z" level=error msg="AccessDeniedException: User: arn:aws:iam::xxx:user/fluentbit-sandbox-clus-eu-west-1 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-west-1:xxx:log-group:/applications/eks-fluentbit/sandbox-cluster:log-stream:\n\tstatus code: 400, request id: 01c6e885-5ffc-4418-8c87-4f87981217dc"
time="2020-09-18T08:19:17Z" level=error msg="AccessDeniedException: User: arn:aws:iam::xxx:user/fluentbit-sandbox-clus-eu-west-1 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-west-1:xxx:log-group:/applications/eks-fluentbit/sandbox-cluster:log-stream:\n\tstatus code: 400, request id: fe14da71-8558-4873-997e-9fa467fa0e92"
time="2020-09-18T08:19:18Z" level=error msg="AccessDeniedException: User: arn:aws:iam::xxx:user/fluentbit-sandbox-clus-eu-west-1 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-west-1:xxx:log-group:/applications/eks-fluentbit/sandbox-cluster:log-stream:\n\tstatus code: 400, request id: b6f3cdd8-ef66-4d8d-bdbb-56ff9d854f38"
time="2020-09-18T08:19:18Z" level=error msg="AccessDeniedException: User: arn:aws:iam::xxx:user/fluentbit-sandbox-clus-eu-west-1 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-west-1:xxx:log-group:/applications/eks-fluentbit/sandbox-cluster:log-stream:\n\tstatus code: 400, request id: cd0bc34a-e4c8-44a3-ab0c-70e71ec273d6"
time="2020-09-18T08:19:18Z" level=error msg="AccessDeniedException: User: arn:aws:iam::xxx:user/fluentbit-sandbox-clus-eu-west-1 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-west-1:xxx:log-group:/applications/eks-fluentbit/sandbox-cluster:log-stream:\n\tstatus code: 400, request id: aac21c1f-e687-4313-93e2-02481ca40919"
time="2020-09-18T08:19:20Z" level=error msg="AccessDeniedException: User: arn:aws:iam::xxx:user/fluentbit-sandbox-clus-eu-west-1 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:eu-west-1:xxx:log-group:/applications/eks-fluentbit/sandbox-cluster:log-stream:\n\tstatus code: 400, request id: a679e4b3-ccc5-41bf-b070-918c43193cfe"
```

Not that in the new version the following line is missing:
```
time="2020-09-18T08:13:03Z" level=info msg="[cloudwatch 0] plugin parameter auto_create_group = 'false'"
```

Also note that the log_group already exists (it is provisioned via CloudFormation in our environment), so even if the auto_create_group property is not read, it should not attempt to create the group anyway since it already exists.

**Comment by davidnewhall** [comment] 2020-09-24 09:38
This parameter no longer exists. With the addition of [dynamic log groups](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/pull/81) in [version 1.4.0](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/releases/tag/v1.4.0), they are always created automatically. The way the plugin detects if the group exists or not is by trying to create the log group.  I agree, this is a regression because it requires elevating the privileges of the application. On the reverse, it always ensures the log group exists, so it's sort of a feature, but it definitely broke in your environment and that's bad. 

When the log group already exists a message like this is emitted:
```
time="2020-09-24T08:51:51Z" level=info msg="[cloudwatch 0] Log group /ecs/twitch-fluentbit-syslog already exists."
```

My cloudformation assigns the following permissions to my task: 

```
- 'logs:CreateLogStream'
- 'logs:DescribeLogStreams'
- 'logs:CreateLogGroup'
- 'logs:PutRetentionPolicy'
- 'logs:PutLogEvents'
```

Hope this helps. We'll have to figure out if we revert this change, or just recommend the new permission. Thoughts?

**Comment by dpryden** [comment] 2020-09-24 16:19
We are running into a similar issue, where we haven't granted `logs:CreateLogGroup`. It looks like the issue is in [`cloudwatch/cloudwatch.go` line 453](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/mainline/cloudwatch/cloudwatch.go#L453) where it checks specifically for `cloudwatchlogs.ErrCodeResourceAlreadyExistsException`. Is it possible to just check for a permission denied error there as well?

I think simply ignoring a permission denied error there would be sufficient. It seems like there are two possible scenarios where this would happen:

1. The log group does not exist, and the task does not have `logs:CreateLogGroup`: in this case, if we ignore the error on creating the log group, we will still get an error in `AddEvent`; I think the result is an error either way. (And has to be.)
2. The log group does exist, but the task does not have `logs:CreateLogGroup`: in this case, if we ignore the error on creating the log group, everything else will work normally.

Am I missing something? It seems like this problem can be trivially fixed by ignoring the error from `CreateLogGroup`. That allows the new behavior to work when the permissions allow it, but also allows the old behavior to work when the permissions only allow what the old behavior needed.

**Comment by davidnewhall** [comment] 2020-09-24 17:48
Ignoring the error is likely the easiest fix.

**Comment by fcoelho** [comment] 2020-09-25 08:31
Depending on an AccessDenied is not something I'd like to see as those would show up in Cloudtrail, making it a bit harder to differentiate between valid traffic and an unusual situation.

Depending on the "log group already exists" error would be ok as I don't think those generate any odd logs. The [documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazoncloudwatchlogs.html#amazoncloudwatchlogs-CreateLogGroup) says I can give the task permissions to use `logs:CreateLogGroup` just on the expected log group, so that can be arranged.

To me the issue of having the application create its own log groups is the potential of creating many unwanted log groups by mistake and having no direct reference to them after the fact. I manage all my infra with code and if I let the application create the log group it means I have to wait for it to be able to attach metric filters or log subscriptions. The use case of ensuring a valid log group exists is interesting, but I usually don't give the task permissions to write to any log groups except their own.

**Comment by davidnewhall** [comment] 2020-09-25 09:06
I'm not opposed to, at all, to adding back the `auto_create_group` parameter. I think defaulting to `true` might be in order given the new dynamic bits. Thoughts?

**Comment by jonathanjuursema** [comment] 2020-09-25 13:55
For our use case just adding back the `auto_create_group` parameter (with a default to `true`) would be just fine. This is in line with the intention going forward, as well as with dynamic log groups. The people who manage their infra with code (us included) and/or the people who prefer a very tight IAM policy (us included) can just opt for the slightly more different road and override the default to false.

I also subscribe to @fcoelho's remark regarding logging excessive "Access Denied" calls in Cloud Trail. We also have logging and notifications on our AWS environment (we noticed the Access Denied errors in our audit logging first) and we're already dealing with enough API calls that we don't want but can't turn off as it is (I'm looking at you, DataDog and AWS Config).

Adding back the parameter, and just setting the default to `true` would be a perfectly fine solution for us. :) 

Thanks for the consideration!

**Closed as completed** 2020-09-28 04:14 UTC

**Comment by jonathanjuursema** [comment] 2020-09-28 07:43
Awesome, thanks for resolving! 🎉

**Comment by PettitWesley** [comment] 2020-09-28 07:53
@jonathanjuursema Note that this has not been released yet, just merged. We'll probably next release in 1.5 weeks when Fluent Bit 1.6 comes out.
